apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: stock-trading-notification-service
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017/notificationsdb
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: APP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: APP_JWT_SECRET
          readinessProbe:
            tcpSocket:
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8087
            initialDelaySeconds: 90
            periodSeconds: 20
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - port: 8087
      targetPort: 8087
